{{- $nvim_dir := ".local/share/nvim" -}}
{{- if eq .osid "windows" -}}
{{- $nvim_dir = "AppData/Local/nvim-data" -}}
{{- end -}}
["{{ $nvim_dir }}/site/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
