{{ $default_refresh := "168h" | quote }}

{{ $nvim_dir := ".local/share/nvim" }}
{{ if eq .osid "windows" }}
{{ $nvim_dir = "AppData/Local/nvim-data" }}
{{ end }}
["{{ $nvim_dir }}/site/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = {{ $default_refresh }}

[".config/eza/theme.yml"]
    type = "file"
    url = "https://raw.githubusercontent.com/eza-community/eza-themes/refs/heads/main/themes/catppuccin.yml"
    refreshPeriod = {{ $default_refresh }}

{{ if eq .osid "linux-centos" }}

[".local/bin/hexyl"]
    type = "archive-file"
    url = "{{ includeTemplate "github_download_url" (dict "repo" "sharkdp/hexyl" "needle" "x86_64-unknown-linux-musl") }}"
    stripComponents = 1
    path = "hexyl"
    executable = true

[".local/bin/ov"]
    type = "archive-file"
    url = "{{ includeTemplate "github_download_url" (dict "repo" "noborus/ov" "needle" "linux_amd64") }}"
    path = "ov"
    executable = true

{{ end }}

{{ if eq .osid "windows" }}

["Documents/PowerShell/Completion/bat.ps1"]
    type = "archive-file"
    url = "{{ includeTemplate "github_download_url" (dict "repo" "sharkdp/bat" "needle" "x86_64-pc-windows-msvc") }}"
    stripComponents = 1
    path = "autocomplete/_bat.ps1"

["Documents/PowerShell/Completion/hyperfine.ps1"]
    type = "archive-file"
    url = "{{ includeTemplate "github_download_url" (dict "repo" "sharkdp/hyperfine" "needle" "x86_64-pc-windows-msvc") }}"
    stripComponents = 1
    path = "autocomplete/_hyperfine.ps1"

{{ end }}
