{{ $default_refresh := "168h" | quote }}

{{ $nvim_dir := ".local/share/nvim" }}
{{ if eq .osid "windows" }}
{{ $nvim_dir = "AppData/Local/nvim-data" }}
{{ end }}
["{{ $nvim_dir }}/site/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = {{ $default_refresh }}

[".config/eza/theme.yml"]
    type = "file"
    url = "https://raw.githubusercontent.com/eza-community/eza-themes/refs/heads/main/themes/catppuccin.yml"
    refreshPeriod = {{ $default_refresh }}

{{ if eq .osid "linux-centos" }}

{{ $hexyl_version := "0.14.0" }}
[".local/bin/hexyl"]
    type = "archive-file"
    url = "https://github.com/sharkdp/hexyl/releases/download/v{{ $hexyl_version }}/hexyl-v{{ $hexyl_version }}-x86_64-unknown-linux-musl.tar.gz"
    stripComponents = 1
    path = "hexyl"
    executable = true

{{ $ov_version := "0.36.0" }}
[".local/bin/ov"]
    type = "archive-file"
    url = "https://github.com/noborus/ov/releases/download/v{{ $ov_version }}/ov_{{ $ov_version }}_linux_amd64.zip"
    path = "ov"
    executable = true

{{ end }}
