[[package]]
winget = "AgileBits.1Password"

[[package]]
winget = "7zip.7zip"

[[package]]
winget = "sharkdp.bat"

[[package]]
scoop = "CascadiaCode-NF-Mono"

[[package]]
winget = "Google.Chrome"

[[package]]
winget = "Kitware.CMake"

[[package]]
winget = "dandavison.delta"

[[package]]
winget = "eza-community.eza"

[[package]]
winget = "Fastfetch-cli.Fastfetch"

[[package]]
winget = "sharkdp.fd"

[[package]]
winget = "junegunn.fzf"

[[package]]
winget = "Git.Git"

[[package]]
winget = "Graphviz.Graphviz"

[[package]]
winget = "sharkdp.hexyl"

[[package]]
winget = "sharkdp.hyperfine"

[[package]]
scoop = "jid"

[[package]]
winget = "jqlang.jq"

[[package]]
winget = "Neovim.Neovim"

[[package]]
winget = "Ninja-build.Ninja"

[[package]]
winget = "JanDeDobbeleer.OhMyPosh"

[[package]]
winget = "noborus.ov"

[[package]]
scoop = "posh-git"

[[package]]
winget = "Microsoft.PowerShell"

[[package]]
winget = "Microsoft.PowerToys"

[[package]]
scoop = "psfzf"

[[package]]
scoop = "python"

[[package]]
winget = "BurntSushi.ripgrep.MSVC"

[[package]]
winget = "Rustlang.Rustup"

[[package]]
winget = "Spotify.Spotify"

[[package]]
winget = "Valve.Steam"

[[package]]
winget = "SublimeHQ.SublimeText.4"

[[package]]
winget = "Telegram.TelegramDesktop"

[[package]]
winget = "astral-sh.uv"

[[package]]
winget = "Microsoft.VisualStudioCode"

[[package]]
winget = "Microsoft.WindowsTerminal"

[[package]]
winget = "WinMerge.WinMerge"

[[package]]
winget = "WireGuard.WireGuard"

[[package]]
winget = "ajeetdsouza.zoxide"

[[package]]
winget = "Meta.Zstandard"
